# Generated by Django 5.2.7 on 2025-11-28 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesLike',
            fields=[
                ('detallesLike_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaLike', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='LIKE', max_length=10)),
                ('esMutuo', models.BooleanField(default=False)),
                ('usuarioEmisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_hechos', to=settings.AUTH_USER_MODEL, verbose_name='Emisor')),
                ('usuarioReceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Receptor')),
            ],
            options={
                'verbose_name': 'Detalle de Like',
                'verbose_name_plural': 'Detalles de Likes',
                'db_table': 'detallesLike',
                'constraints': [models.UniqueConstraint(models.F('usuarioEmisor'), models.F('usuarioReceptor'), name='unique_like_interaction')],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaMatch', models.DateTimeField(auto_now_add=True)),
                ('afinidad', models.FloatField(default=0.0)),
                ('estadoMatch', models.CharField(default='ACTIVO', max_length=50)),
                ('usuarioA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_a', to=settings.AUTH_USER_MODEL)),
                ('usuarioB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'db_table': 'match',
                'constraints': [models.UniqueConstraint(models.F('usuarioA'), models.F('usuarioB'), name='unique_match_pair')],
            },
        ),
    ]
